services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - contenedor_app1
    networks:
      - app-network
    restart: always

  contenedor_app1:
    image: imagen_app1
    build: .
    volumes:
      - ./app1:/var/www/html
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
